services:
  app:
    build: ./.docker/node
    volumes:
      - .:/home/node/app
    ports:
      - '3000:3000'

  mongodb:
    build:
      context: ./.docker/mongodb
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27019
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27019:27019'
    restart: unless-stopped
    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test:
        [
          'CMD',
          'mongosh',
          'admin',
          '--port',
          '27019',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
